---
repos:
  - repo: meta
    hooks:
      # - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test
        args: [--pytest-test-first]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.0
    hooks:
      - id: check-github-workflows
        name: validate github workflows
        args: ["--verbose"]

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.9.0
    hooks:
      - id: zizmor

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 40.14.3
    hooks:
      - id: renovate-config-validator

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        name: validate pyproject.toml
        additional_dependencies: ["validate-pyproject-schema-store[all]"]

  - repo: local
    hooks:
      - id: ruff format
        name: ruff format
        language: system
        entry: uv run ruff format
        types: [python]
        pass_filenames: true

      - id: ruff check
        name: ruff check
        language: system
        entry: uv run ruff check --fix
        types: [python]
        pass_filenames: true

      - id: deal lint
        name: deal lint
        language: system
        entry: uv run python3 -m deal lint
        types: [python]

      - id: mypy
        name: mypy
        language: system
        entry: uv run mypy
        types: [python]
