---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test
        args: [--pytest-test-first]

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.16.1
    hooks:
      - id: renovate-config-validator
