[pre-commit]
    parallel = true

[pre-commit.commands.format]
    name = "format the code"
    run = "timeout --verbose 5 uv --no-config run --frozen ruff format {staged_files}"
    stage_fixed = true
    glob = "*.py"

[pre-commit.commands.lint]
    name = "lint and fix the code"
    run = "timeout --verbose 5 uv --no-config run --frozen ruff check --fix {staged_files}"
    stage_fixed = true
    glob = "*.py"

[pre-commit.commands.lint_types]
    name = "lint types in code"
    run = "timeout --verbose 5 uv --no-config run --frozen mypy {staged_files}"
    glob = "*.py"

# TODO: deal lint fails. possibly a bug in deal ?
#[pre-commit.commands.lint_contracts]
#    name = "lint contracts in code"
#    run = "timeout --verbose 5 uv --no-config run --frozen python3 -m deal lint {staged_files}"
#    glob = "*.py"
#    exclude = [
#        "tests/*"
#    ]

[pre-commit.commands.legacy]
    run = "timeout --verbose 5 uv --no-config run --frozen pre-commit run --all-files --show-diff-on-failure"
    follow = true
    stage_fixed = true
