[pre-commit]
    parallel = true

[pre-commit.commands.format]
    name = "lint, fix, and format the code"
    run = "uv run --frozen ruff check --fix {staged_files} && uv run --frozen ruff format {staged_files}"
    stage_fixed = true
    glob = "*.py"
    tags = ["lint", "format", "python"]

[pre-commit.commands.lint_types]
    name = "check static types"
    run = "uv run --frozen mypy {staged_files}"
    glob = "*.py"
    tags = ["lint", "python"]

[pre-commit.commands.shellcheck]
    name = "run shellcheck"
    run = "uv run shellcheck {staged_files}"
    glob = "./scripts/*"
    tags = ["lint", "shell"]

# TODO: deal lint fails. possibly a bug in deal ?
#[pre-commit.commands.lint_contracts]
#    name = "lint contracts in code"
#    run = "uv run --frozen python3 -m deal lint {staged_files}"
#    glob = "*.py"
#    exclude = [
#        "tests/*"
#    ]

[pre-commit.commands.legacy]
    run = "uv run --frozen pre-commit run --all-files --show-diff-on-failure"
    follow = true
    stage_fixed = true
